# ECHONET Lite EV充放電器テンプレート
# EV充放電器専用のマッピング設定

# ECHONET Lite EV充放電器テンプレート（V2G対応）
# EV充放電器専用のマッピング設定（Vehicle-to-Grid対応）

template:
  id: "echonet_lite_charger_discharger"
  name: "ECHONET Lite EV充放電器"
  description: "ECHONET Lite対応EV充放電器のテンプレート（V2G対応）"
  version: "1.0"
  
  # デバイス情報
  device:
    protocol: "echonet_lite"
    class_group: 0x02  # 住宅・設備関連機器クラスグループ
    class: 0xA1        # 電気自動車充電器クラス
    instance: 0x01     # インスタンス番号
  
  # OCPP変数とECHONET Lite EPCのマッピング
  variables:
    # 利用可能状態
    - ocpp_name: "AvailabilityState"
      description: "充放電器の利用可能状態"
      type: "echonet_lite"
      epc: 0xB0        # 動作状態
      data_type: "uint8"
      enum:
        0x30: "Available"    # 利用可能
        0x31: "Occupied"     # 使用中
        0x32: "Unavailable"  # 利用不可
        0x33: "Faulted"      # 故障
    
    # 電力量計測値（充電）
    - ocpp_name: "MeterValue.Energy.Active.Import.Register"
      description: "累積充電電力量（kWh）"
      type: "echonet_lite"
      epc: 0xE0        # 積算電力量計測値
      data_type: "uint32"
      scale: 0.001      # スケール（Wh → kWh）
      unit: "kWh"
    
    # 電力量計測値（放電）
    - ocpp_name: "MeterValue.Energy.Active.Export.Register"
      description: "累積放電電力量（kWh）"
      type: "echonet_lite"
      epc: 0xE4        # 積算放電電力量計測値
      data_type: "uint32"
      scale: 0.001      # スケール（Wh → kWh）
      unit: "kWh"

    # 電力量計測値（V2G放電）
    - ocpp_name: "MeterValue.Energy.Active.Export.Register"
      description: "累積V2G放電電力量（kWh）"
      type: "echonet_lite"
      epc: 0xE4        # 積算放電電力量計測値
      data_type: "uint32"
      scale: 0.001      # スケール（Wh → kWh）
      unit: "kWh"
    
    # コネクタ状態
    - ocpp_name: "Connector.Status"
      description: "コネクタの状態"
      type: "echonet_lite"
      epc: 0xC0        # 接続状態
      data_type: "uint8"
      enum:
        0x30: "Available"    # 利用可能
        0x31: "Occupied"     # 使用中
        0x32: "Reserved"     # 予約済み
        0x33: "Faulted"      # 故障
    
    # 充電電力
    - ocpp_name: "MeterValue.Power.Active.Import"
      description: "充電電力（kW）"
      type: "echonet_lite"
      epc: 0xE1        # 瞬時電力計測値
      data_type: "uint16"
      scale: 0.1        # スケール（W → kW）
      unit: "kW"
    
    # 放電電力
    - ocpp_name: "MeterValue.Power.Active.Export"
      description: "放電電力（kW）"
      type: "echonet_lite"
      epc: 0xE5        # 瞬時放電電力計測値
      data_type: "uint16"
      scale: 0.1        # スケール（W → kW）
      unit: "kW"

    # V2G放電電力
    - ocpp_name: "MeterValue.Power.Active.Export"
      description: "V2G放電電力（kW）"
      type: "echonet_lite"
      epc: 0xE5        # 瞬時放電電力計測値
      data_type: "uint16"
      scale: 0.1        # スケール（W → kW）
      unit: "kW"
    
    # 充電電圧
    - ocpp_name: "MeterValue.Voltage"
      description: "充電電圧（V）"
      type: "echonet_lite"
      epc: 0xE2        # 瞬時電圧計測値
      data_type: "uint16"
      scale: 1.0        # スケール
      unit: "V"
    
    # 充電電流
    - ocpp_name: "MeterValue.Current.Import"
      description: "充電電流（A）"
      type: "echonet_lite"
      epc: 0xE3        # 瞬時電流計測値
      data_type: "uint16"
      scale: 0.1        # スケール（A）
      unit: "A"
    
    # 運転モード（V2G対応）
    - ocpp_name: "OperationMode"
      description: "運転モード"
      type: "echonet_lite"
      epc: 0xB1        # 運転モード設定
      data_type: "uint8"
      enum:
        0x41: "Charging"     # 充電モード
        0x42: "V2GDischarging"  # V2G放電モード
        0x43: "Standby"      # 待機モード
        0x44: "Fault"        # 故障モード

    # 運転モード（充放電対応）
    - ocpp_name: "OperationMode"
      description: "運転モード"
      type: "echonet_lite"
      epc: 0xDA        # 運転モード設定
      data_type: "uint8"
      enum:
        0x42: "Charging"     # 充電
        0x43: "Discharging"  # 放電
        0x44: "ChargingDischarging"  # 充放電
        0x45: "Auto"         # 自動
        0x47: "Stop"         # 停止
        0x48: "Standby"      # 待機
  
  # コマンドマッピング
  commands:
    # 充電開始
    - ocpp_name: "StartTransaction"
      description: "充電開始コマンド"
      type: "echonet_lite"
      epc: 0x80        # 運転設定
      data_type: "uint8"
      enum:
        0x30: "Start"   # 開始
        0x31: "Stop"    # 停止

    # 充電開始
    - ocpp_name: "StartTransaction"
      description: "充電開始コマンド"
      type: "echonet_lite"
      epc: 0xDA        # 運転モード設定
      data_type: "uint8"
      enum:
        0x42: "Charging"   # 充電
        0x47: "Stop"       # 停止
    
    # 充電停止
    - ocpp_name: "StopTransaction"
      description: "充電停止コマンド"
      type: "echonet_lite"
      epc: 0x80        # 運転設定
      data_type: "uint8"
      enum:
        0x31: "Stop"    # 停止

    # 充電停止
    - ocpp_name: "StopTransaction"
      description: "充電停止コマンド"
      type: "echonet_lite"
      epc: 0xDA        # 運転モード設定
      data_type: "uint8"
      enum:
        0x47: "Stop"    # 停止
    
    # 放電開始
    - ocpp_name: "StartDischarging"
      description: "放電開始コマンド"
      type: "echonet_lite"
      epc: 0x80        # 運転設定
      data_type: "uint8"
      enum:
        0x32: "Discharge"  # 放電開始
        0x31: "Stop"       # 停止

    # 放電開始
    - ocpp_name: "StartDischarging"
      description: "放電開始コマンド"
      type: "echonet_lite"
      epc: 0xDA        # 運転モード設定
      data_type: "uint8"
      enum:
        0x43: "Discharging"  # 放電
        0x47: "Stop"         # 停止
    
    # 放電停止
    - ocpp_name: "StopDischarging"
      description: "放電停止コマンド"
      type: "echonet_lite"
      epc: 0x80        # 運転設定
      data_type: "uint8"
      enum:
        0x31: "Stop"    # 停止

    # 放電停止
    - ocpp_name: "StopDischarging"
      description: "放電停止コマンド"
      type: "echonet_lite"
      epc: 0xDA        # 運転モード設定
      data_type: "uint8"
      enum:
        0x47: "Stop"    # 停止 