name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libboost-all-dev libssl-dev libyaml-cpp-dev libjsoncpp-dev libspdlog-dev pkg-config nlohmann-json3-dev libmodbus-dev
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug --parallel
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        if [ -f "CTestTestfile.cmake" ]; then
          ctest -C Debug --output-on-failure --verbose
        else
          echo "No tests found"
        fi
      
  static-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy cppcheck clang-format
        
    - name: Run Cppcheck
      run: |
        cppcheck --enable=all --std=c++17 --suppress=missingIncludeSystem --error-exitcode=1 -I include/ include/ src/ || true
      
    - name: Check code formatting
      run: |
        find include src tests -name "*.cpp" -o -name "*.h" | xargs clang-format -i --style=file || true
        git diff --exit-code || echo "Code formatting issues found"
        
  package:
    needs: [build, static-analysis]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libboost-all-dev libssl-dev libyaml-cpp-dev libjsoncpp-dev libspdlog-dev pkg-config nlohmann-json3-dev libmodbus-dev
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release --parallel
      
    - name: Package
      working-directory: ${{github.workspace}}/build
      run: |
        if command -v cpack >/dev/null 2>&1; then
          cpack -G DEB || echo "Packaging failed, but continuing"
        else
          echo "CPack not available"
        fi
      
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: ocpp-gateway-deb
        path: ${{github.workspace}}/build/*.deb
        if-no-files-found: ignore